node {
   def commit_id
   stage('step a') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'node_11') {
       sh "cd basics && npm install --only=dev"
       sh 'cd basics && npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'galt99') {
       def app = docker.build("galt99/new:${commit_id}", './basics').push()
     }
   }  
   stage('docker run') {
     sh label: '', script: '''
      docker run --rm -tid --name docker_test -p 3000 galt99/new:latest
      docker kill docker_test
      port = docker port CONTAINER docker_test
      curl localhost -p $ port
      '''
     }
   }

